version: '3'

services:
  web:
    build: .
    command: bash -c "sleep 5 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    
    expose:
      - "8000"
    depends_on:
      - db
    networks: 
      - backend

  db:
    image: postgis/postgis
    container_name: postgis
    volumes:
      - .:/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=diogo
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgis
    networks: 
      - backend
      
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=5454
    depends_on:
      - db
    networks: 
      - backend
      
networks:
  backend:
    driver: "bridge"